sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: Takeaway-test
    username: root
    password: root
  alioss:
    bucket-name: takeaway-test
    endpoint: oss-cn-chengdu.aliyuncs.com